### ISSUE TITLE
TODO list 

### ISSUE THREAD

**Issue by SebaGraz** [mschauer/ZigZagBoomerang.jl#6]
- [ ] Implement the exact subsampling algorithm where ∇ϕ(x) is estimated by an unbiased estimator ∇ϕ_tilde(x) (the standard example is Big Data with i.i.d observations. Then the target density is given by a product of terms -> gradient of the negative log density is given by a sum of terms. Subsampling by picking randomly one term of the sum.

**Comment by mschauer** [comment]
- [ ] Scaling in the 1-d Boomerang
- [ ] Local n-d Boomerang

**Comment by SebaGraz** [comment]
I want to propose the following: 

1. To have the d dimensional implementation as the default implementation and drop the 1-dimensional implementation
2. To group the implementations for not factorised (Bouncy and Boomerang) and factorised pdmps (Zig-Zag and Fact. Boomerang).
2. To have the Local implementation (with the PriorityQueue) of the factorised pdmps as the default implementation for those algorithms (Zig-Zag and Fact. Boomerang). When the graph is not specified, then assume a  fully connected graph

**Comment by SebaGraz** [comment]
- [ ] save the bounds `a` and `b` and use them for both the evaluation of `\lambda_bar` and `poisson_time`. (Now we compute them twice)

**Comment by mschauer** [comment]
Let's keep the 1-d version intact for didactical purposes, but the high dimensional should be the default

**Comment by mschauer** [comment]
- [ ] Allow for change of reference measure in FactBoomerang
